name: Python Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    
    - name: Lint with ruff
      run: |
        # Run ruff on Python files
        ruff check $(git ls-files '*.py')
      
    - name: Suggest fixes (on failure)
      if: failure()
      run: |
        echo "::warning::Linting failed. You can fix most issues automatically by running:"
        echo "::warning::pip install ruff"
        echo "::warning::python USER_DIR/fix_linting.py" 